firefly-db:
  # environment variables
  configs:
    POSTGRES_USER: firefly
    PGPASSWORD: wO9wrXo7fESnUsFh
    TZ: US/Eastern
  storage:
    existingClaim: hl-fireflyiii-firefly-db-storage-claim
  backup:
    enabled: false

firefly-iii:
  config:
    env:
      DB_HOST: hl-fireflyiii-firefly-db
      DB_CONNECTION: pgsql
      DB_PORT: 5432
      DB_DATABASE: firefly
      DB_USERNAME: firefly
      TZ: US/Eastern
  image:
    tag: version-6.2.12
  ingress:
    enabled: true
    hosts:
      - 'jam.jelly.io'

importer:
  fireflyiii:
    url: hl-fireflyiii-firefly-iii
    vanityUrl: "http://jam.jelly.io:80"
  config:
    env:
      TZ: US/Eastern
  image:
    tag: version-1.6.2
  ingress:
    enabled: true
    hosts:
      - 'import.jam.jelly.io'
