firefly-db:
  # environment variables
  configs:
    POSTGRES_USER: firefly
    PGPASSWORD: wO9wrXo7fESnUsFh
    TZ: US/Eastern
  storage:
    existingClaim: hl-fireflyiii-firefly-db-storage-claim
  backup:
    enabled: false

firefly-iii:
  config:
    env:
      DB_HOST: hl-fireflyiii-firefly-db
      DB_CONNECTION: pgsql
      DB_PORT: 5432
      DB_DATABASE: firefly
      DB_USERNAME: firefly
      TZ: US/Eastern
  image:
    tag: version-6.4.0
  ingress:
    enabled: true
    hosts:
      - 'firefly.jamjelly.io'
  persistence:
    existingClaim: hl-fireflyiii-firefly-db-storage-claim

importer:
  fireflyiii:
    url: hl-fireflyiii-firefly-iii
    vanityUrl: "http://firefly.jamjelly.io:80"
  config:
    env:
      TZ: US/Eastern
  image:
    tag: version-1.7.10
  ingress:
    enabled: true
    hosts:
      - 'import.jamjelly.io'
